# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Projects"
url = "/projects"
weight = 2

[[main]]
name = "Car Dealership Web Application"
parent = "Projects"
pageRef = "projects/carapp/_index.md"
url = "/projects/carapp/_index.md"
weight = 2

[[main]]
name = "Security Tools"
parent = "Projects"
pageRef = "projects/sectools/_index.md"
url = "/securitytools.md"
weight = 2

[[main]]
name = "Secure E-Commerce Web Application"
parent = "Projects"
pageRef = "/projects/ecommerce/_index.md"
url = "/projects/ecommerce/_index.md"
weight = 2

[[main]]
name = "Scalable Data Lakehouse Pipeline"
parent = "Projects"
pageRef = "/projects/datapipeline/_index.md"
url = "/projects/datapipeline/_index.md"
weight = 2

[[main]]
name = "Certifications"
url = "/certifications"
weight = 3

[[main]]
name = "AWS Cloud Practitioner"
parent = "Certifications"
pageRef = "certifications/certs/_aws.md"
url = "/certifications/certs/_aws.md"
weight = 3

[[main]]
name = "Security+"
parent = "Certifications"
pageRef = "certifications/certs/_sec.md"
url = "/certifications/certs/_sec.md"
weight = 3

[[main]]
name = "Blog Posts"
url = "/posts"
weight = 4

[[main]]
name = "Resume"
url = "https://resume-ms.s3.amazonaws.com/Sajjad_Mohammed+-+Resume.pdf"
weight = 5

[[main]]
identifier = "linkedin" 
pre = "linkedin"
url = "https://www.linkedin.com/in/mohammed-sajjad-141889214/"
weight = 6

[[main]]
identifier = "github" 
pre = "github"
url = "https://github.com/shadowg9?tab=repositories"
weight = 7

#[[main]]
#  name = "Parent"
#  weight = 20

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
